CRITICAL - 2022-01-07 18:08:53 --> syntax error, unexpected '}', expecting ';' or ','
#0 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\form...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\form...')
#3 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(10): spl_autoload_call('App\\Models\\form...')
#4 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-01-07 18:09:16 --> syntax error, unexpected end of file, expecting ';' or ','
#0 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\form...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\form...')
#3 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(10): spl_autoload_call('App\\Models\\form...')
#4 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-01-07 18:09:19 --> syntax error, unexpected end of file, expecting ';' or ','
#0 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\form...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\form...')
#3 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(10): spl_autoload_call('App\\Models\\form...')
#4 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-01-07 18:12:56 --> syntax error, unexpected '}', expecting ';' or ','
#0 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\form...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\form...')
#3 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(10): spl_autoload_call('App\\Models\\form...')
#4 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-01-07 18:14:37 --> syntax error, unexpected '}', expecting ';' or ','
#0 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\form...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\form...')
#3 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(10): spl_autoload_call('App\\Models\\form...')
#4 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-01-07 18:14:38 --> syntax error, unexpected '}', expecting ';' or ','
#0 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\form...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\form...')
#3 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(10): spl_autoload_call('App\\Models\\form...')
#4 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-01-07 18:14:39 --> syntax error, unexpected '}', expecting ';' or ','
#0 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\form...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\form...')
#3 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(10): spl_autoload_call('App\\Models\\form...')
#4 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-01-07 18:14:39 --> syntax error, unexpected '}', expecting ';' or ','
#0 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\form...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\form...')
#3 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(10): spl_autoload_call('App\\Models\\form...')
#4 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-01-07 18:19:24 --> syntax error, unexpected '}', expecting ';' or ','
#0 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\form...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\form...')
#3 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(10): spl_autoload_call('App\\Models\\form...')
#4 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-01-07 18:22:27 --> syntax error, unexpected '}', expecting ';' or ','
#0 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\form...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\form...')
#3 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(10): spl_autoload_call('App\\Models\\form...')
#4 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-01-07 18:24:06 --> syntax error, unexpected 'protected' (T_PROTECTED), expecting ';' or ','
#0 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\form...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\form...')
#3 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(10): spl_autoload_call('App\\Models\\form...')
#4 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-01-07 18:27:14 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-07 18:27:14 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-07 18:44:44 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-07 18:44:44 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-07 18:53:12 --> No database selected
CRITICAL - 2022-01-07 18:53:12 --> Call to a member function getResult() on bool
#0 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#1 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#2 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#3 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#4 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#6 {main}
ERROR - 2022-01-07 18:53:52 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-07 18:53:52 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-01-07 18:56:06 --> syntax error, unexpected ''codigo'' (T_CONSTANT_ENCAPSED_STRING), expecting variable (T_VARIABLE)
#0 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\form...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\form...')
#3 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(10): spl_autoload_call('App\\Models\\form...')
#4 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-01-07 18:57:28 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-07 18:57:28 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-07 19:02:25 --> Error connecting to the database: Unknown database 'my_database'
CRITICAL - 2022-01-07 19:02:25 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'my_database'
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-07 19:02:54 --> No database selected
CRITICAL - 2022-01-07 19:02:54 --> Call to a member function getResult() on bool
#0 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#1 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#2 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#3 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#4 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#6 {main}
ERROR - 2022-01-07 19:03:26 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-07 19:03:26 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-07 19:26:10 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-07 19:26:10 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-07 19:26:18 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-07 19:26:18 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-07 19:30:14 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-07 19:30:14 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-07 19:30:15 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-07 19:30:15 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-07 19:31:26 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-07 19:31:26 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-07 19:32:08 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-07 19:32:08 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-07 19:32:09 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-07 19:32:09 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-07 19:34:37 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-07 19:34:37 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-07 19:34:38 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-07 19:34:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-07 19:34:38 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-07 19:34:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-07 19:34:39 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-07 19:34:39 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-01-07 19:48:42 --> syntax error, unexpected '$this' (T_VARIABLE), expecting function (T_FUNCTION) or const (T_CONST)
#0 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\testing\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Form...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Form...')
#3 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(10): spl_autoload_call('App\\Models\\Form...')
#4 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-01-07 19:50:19 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-07 19:50:19 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-07 20:02:11 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-07 20:02:11 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-07 20:02:13 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-07 20:02:13 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-01-07 20:03:11 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-01-07 20:03:11 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\testing\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\testing\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\testing\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\testing\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\testing\app\Controllers\Formularios.php(11): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\testing\system\CodeIgniter.php(825): App\Controllers\Formularios->index()
#6 C:\xampp\htdocs\testing\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Formularios))
#7 C:\xampp\htdocs\testing\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\testing\public\index.php(38): CodeIgniter\CodeIgniter->run()
#9 {main}
